Option Strict Off
Option Explicit On

Imports CheckBook
Imports CheckBookLib

Public Class ImportHandlerDeposits
    Implements IImportHandler

    Public ReadOnly Property blnAllowNew As Boolean Implements IImportHandler.blnAllowNew
        Get
            Return False
        End Get
    End Property

    Public Sub AutoNewSearch(objImportedTrx As ImportedTrx, objReg As Register, ByRef colMatches As ICollection(Of Integer), ByRef blnExactMatch As Boolean) Implements IImportHandler.AutoNewSearch

    End Sub

    Public Function blnAlternateAutoNewHandling(objImportedTrx As ImportedTrx, objReg As Register) As Boolean Implements IImportHandler.blnAlternateAutoNewHandling
        Return False
    End Function

    Public Function strAutoNewValidationError(objImportedTrx As ImportedTrx, blnAllowBankNonCard As Boolean) As String Implements IImportHandler.strAutoNewValidationError
        Return Nothing
    End Function

    Public Function lngStatusSearch(objImportedTrx As ImportedTrx, objReg As Register) As Integer Implements IImportHandler.lngStatusSearch
        Dim colMatches As ICollection(Of Integer) = Nothing
        Dim lngIndex As Integer
        Dim blnExactMatch As Boolean
        objReg.MatchPayee(objImportedTrx.datDate, 7, objImportedTrx.strDescription, True, colMatches, blnExactMatch)
        If colMatches.Count > 0 Then
            lngIndex = gdatFirstElement(colMatches)
            If Not objReg.objTrx(lngIndex).blnAutoGenerated Then
                Return lngIndex
            End If
        End If
        Return 0
    End Function

End Class
