Option Strict Off
Option Explicit On

Imports CheckBookLib

Public Class ImportHandlerDeposits
    Implements IImportHandler

    Public Function lngStatusSearch(objImportedTrx As ImportedTrx, objReg As Register) As Integer Implements IImportHandler.lngStatusSearch
        Dim colMatches As ICollection(Of Integer) = Nothing
        Dim lngIndex As Integer
        Dim blnExactMatch As Boolean
        objReg.MatchPayee(objImportedTrx.datDate, 7, objImportedTrx.strDescription, True, colMatches, blnExactMatch)
        If colMatches.Count > 0 Then
            lngIndex = gdatFirstElement(colMatches)
            If Not objReg.objTrx(lngIndex).blnAutoGenerated Then
                Return lngIndex
            End If
        End If
        Return 0
    End Function

End Class
