Option Strict On
Option Explicit On

Public Class FilterFakeOnly
    Implements ISearchFilter

    Public Function blnInclude(objTrx As Trx) As Boolean Implements ISearchFilter.blnInclude
        Return objTrx.blnFake And Not objTrx.blnAutoGenerated
    End Function

    Public Overrides Function ToString() As String
        Return "Fake (but not Generated)"
    End Function
End Class
