Option Strict Off
Option Explicit On

Imports CheckBookLib

Friend Class ShowRegisterForm
    Inherits System.Windows.Forms.Form
    '2345667890123456789012345678901234567890123456789012345678901234567890123456789012345

    Private Structure ShowRegElement
        Dim objAccount As Account
        Dim objReg As Register
    End Structure

    Private maudtElement() As ShowRegElement
    Private mintElements As Short

    Private Sub cmdCancel_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdCancel.Click
        Me.Close()
    End Sub

    Private Sub cmdDeleteRegister_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdDeleteRegister.Click
        Dim objTrx As Trx
        Dim objReg As Register
        Dim objOtherReg As Register
        Dim lngTrxIdx As Integer
        Dim objXfer As TransferManager

        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to delete registers.")
                Exit Sub
            End If

            If gcolForms().Count() <> 1 Then
                MsgBox("You may not delete a register while other windows are open.", MsgBoxStyle.Critical)
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                If .objReg Is Nothing Then
                    MsgBox("You must select a register, not an account.", MsgBoxStyle.Information)
                    Exit Sub
                End If
                If .objAccount.blnUnsavedChanges Then
                    MsgBox("You may not delete a register from an account " & "with unsaved changes.", MsgBoxStyle.Critical)
                    Exit Sub
                End If
                If .objAccount.colRegisters.Count() <= 1 Then
                    MsgBox("You may not delete the last register from an account.", MsgBoxStyle.Critical)
                    Exit Sub
                End If
                objReg = .objReg
                If MsgBox("Do you really want to delete register """ & objReg.strTitle & """?", MsgBoxStyle.OkCancel + MsgBoxStyle.DefaultButton2) <> MsgBoxResult.Ok Then
                    Exit Sub
                End If
                If MsgBox("Are you really sure you want to delete it?", MsgBoxStyle.OkCancel + MsgBoxStyle.DefaultButton2) <> MsgBoxResult.Ok Then
                    Exit Sub
                End If
                MsgBox("Will delete all transfers to/from other registers.", MsgBoxStyle.Information)
                'Now look for non-generated transfers and delete them,
                'so the other half of the transfer is deleted from whatever
                'register it belongs to. Don't worry about generated transfers,
                'because they won't be recreated once this register is deleted.
                'Can't use a "For" loop here because the upper limit changes
                'if Trx are deleted.
                lngTrxIdx = 1
                Do
                    If lngTrxIdx > objReg.lngTrxCount Then
                        Exit Do
                    End If
                    objTrx = objReg.objTrx(lngTrxIdx)
                    If Not objTrx.blnAutoGenerated Then
                        If objTrx.lngType = Trx.TrxType.glngTRXTYP_TRANSFER Then
                            objXfer = New TransferManager
                            objOtherReg = .objAccount.objFindReg(objTrx.strTransferKey)
                            objXfer.DeleteTransfer(objReg, lngTrxIdx, objOtherReg)
                            'Step back, because the next iteration must try
                            'the same index or else we'll skip a trx.
                            lngTrxIdx = lngTrxIdx - 1
                        End If
                    End If
                    lngTrxIdx = lngTrxIdx + 1
                Loop
                .objReg.blnDeleted = True
                .objAccount.SetChanged()
            End With
            MsgBox("Register deleted. Will quit program now, to save this change to the account.", MsgBoxStyle.Information)
            CBMainForm.Close()

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdNewAccount_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdNewAccount.Click
        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to create accounts.")
                Exit Sub
            End If

            If gblnAskAndCreateAccount() Then
                MsgBox("Account will appear the next time you start the software.", MsgBoxStyle.Information)
            End If

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdDeleteAccount_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdDeleteAccount.Click
        Dim strNameRoot As String

        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to delete accounts.")
                Exit Sub
            End If

            If gcolForms().Count() <> 1 Then
                MsgBox("You may not delete an account while other windows are open.", MsgBoxStyle.Critical)
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                strNameRoot = Replace(LCase(.objAccount.strFileLoaded), ".act", "")
                If MsgBox("Are you sure you want to delete account """ & .objAccount.strTitle & """?", MsgBoxStyle.Question + MsgBoxStyle.OkCancel + MsgBoxStyle.DefaultButton2) <> MsgBoxResult.Ok Then
                    Exit Sub
                End If
                If MsgBox("Are you REALLY, REALLY, SURE you want to delete account """ & .objAccount.strTitle & """?", MsgBoxStyle.Question + MsgBoxStyle.OkCancel + MsgBoxStyle.DefaultButton2) <> MsgBoxResult.Ok Then
                    Exit Sub
                End If
            End With
            DeleteAccount(strNameRoot)
            MsgBox("Account deleted. Will quit program now, to save this change.", MsgBoxStyle.Information)
            CBMainForm.Close()

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub DeleteAccount(ByVal strNameRoot As String)
        Dim strFile As String

        Try

            Do
                strFile = Dir(gstrBackupPath() & "\" & strNameRoot & ".act.*")
                If strFile = "" Then
                    Exit Do
                End If
                Kill(gstrBackupPath() & "\" & strFile)
            Loop

            strFile = gstrAccountPath() & "\" & strNameRoot & ".rep"
            If Dir(strFile) <> "" Then
                Kill(strFile)
            End If

            'It looks for ACT files to find accounts, so delete this one last
            'in case it crashes deleting other files. So you can try again.
            strFile = gstrAccountPath() & "\" & strNameRoot & ".act"
            If Dir(strFile) <> "" Then
                Kill(strFile)
            End If

            Exit Sub
        Catch ex As Exception
            gNestedException(ex)
        End Try
    End Sub

    Private Sub cmdNewRegister_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdNewRegister.Click
        Dim strName As String
        Dim intHighestKey As Short
        Dim objReg As Register

        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to create a new register.")
                Exit Sub
            End If

            strName = InputBox("Name of new register:", "New Register")
            If strName = "" Then
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                If MsgBox("Do you really want to create a new register named """ & strName & """ in account """ & .objAccount.strTitle & """?", MsgBoxStyle.Question + MsgBoxStyle.OkCancel + MsgBoxStyle.DefaultButton2) <> MsgBoxResult.Ok Then
                    Exit Sub
                End If
                For Each objReg In .objAccount.colRegisters
                    If Val(objReg.strRegisterKey) > intHighestKey Then
                        intHighestKey = Val(objReg.strRegisterKey)
                    End If
                Next objReg
                .objAccount.CreateRegister(CStr(intHighestKey + 1), strName, True, False)
                .objAccount.SetChanged()
                MsgBox("New register has been added to account and will appear the " & "next time you start the software.", MsgBoxStyle.Information)
            End With

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdSetAccountName_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdSetAccountName.Click
        Dim strName As String

        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to set the account name.")
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                strName = .objAccount.strTitle
                strName = InputBox("Enter new account title:", "Account Title", strName)
                If strName = "" Then
                    Exit Sub
                End If
                .objAccount.strTitle = strName
                MsgBox("Account title change will take effect the next time " & "you start the software.", MsgBoxStyle.Information)
            End With

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdShowRegister_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdShowRegister.Click
        Try

            If lstRegisters.SelectedIndex < 0 Then
                MsgBox("Please select a register first.", MsgBoxStyle.Critical)
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                If .objReg Is Nothing Then
                    MsgBox("You must select a register, not an account.", MsgBoxStyle.Information)
                    Exit Sub
                End If
                gShowRegister(.objAccount, .objReg, Nothing)
            End With
            Me.Close()

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdRegProperties_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdRegProperties.Click
        Dim objProps As RegPropertiesForm

        Try

            If Not gobjSecurity.blnIsAdministrator Then
                MsgBox("Your login is not authorized to set register properties.")
                Exit Sub
            End If

            If lstRegisters.SelectedIndex < 0 Then
                MsgBox("Please select a register first.", MsgBoxStyle.Critical)
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                If .objReg Is Nothing Then
                    MsgBox("You must select a register, not an account.", MsgBoxStyle.Information)
                    Exit Sub
                End If
                objProps = New RegPropertiesForm
                objProps.ShowModal(.objReg)
            End With

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub cmdRegen_Click(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles cmdRegen.Click
        Dim strRegisterEndDate As String

        Try

            If lstRegisters.SelectedIndex < 0 Then
                MsgBox("Please select an account first.", MsgBoxStyle.Critical)
                Exit Sub
            End If

            With maudtElement(lstRegisters.SelectedIndex)
                If Not .objReg Is Nothing Then
                    MsgBox("You must select an account, not a register.", MsgBoxStyle.Information)
                    Exit Sub
                End If
                strRegisterEndDate = InputBox("Enter ending date to generate transactions through:", "Ending Date", gstrFormatDate(DateAdd(Microsoft.VisualBasic.DateInterval.Day, 90, Now)))
                If strRegisterEndDate <> "" Then
                    If gblnValidDate(strRegisterEndDate) Then
                        System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.WaitCursor
                        .objAccount.RecreateGeneratedTrx(CDate(strRegisterEndDate))
                        Me.Activate()
                        System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.Default
                    Else
                        MsgBox("Invalid date.")
                    End If
                End If
            End With

            Exit Sub
        Catch ex As Exception
            System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.Default
            gTopException(ex)
        End Try
    End Sub

    Private Sub ShowRegisterForm_Load(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles MyBase.Load
        Dim objAccount As Account
        Dim objReg As Register

        Try

            Me.Width = 540
            Me.Height = 450

            Erase maudtElement
            mintElements = 0
            lstRegisters.Items.Clear()

            For Each objAccount In gcolAccounts
                mintElements = mintElements + 1
                ReDim Preserve maudtElement(mintElements - 1)
                With maudtElement(mintElements - 1)
                    .objAccount = objAccount
                    'UPGRADE_NOTE: Object maudtElement().objReg may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
                    .objReg = Nothing
                    'UPGRADE_NOTE: Object maudtElement().objLoaded may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
                    .objReg = Nothing
                    lstRegisters.Items.Add("--- Registers in Account " & objAccount.strTitle & " ---")
                End With
                For Each objReg In objAccount.colRegisters
                    mintElements = mintElements + 1
                    ReDim Preserve maudtElement(mintElements - 1)
                    With maudtElement(mintElements - 1)
                        .objAccount = objAccount
                        .objReg = objReg
                        lstRegisters.Items.Add(.objReg.strTitle)
                    End With
                Next objReg
            Next objAccount

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub lstRegisters_SelectedIndexChanged(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles lstRegisters.SelectedIndexChanged
        Dim blnRegisterSelected As Boolean

        Try

            blnRegisterSelected = Not (maudtElement(lstRegisters.SelectedIndex).objReg Is Nothing)
            cmdSetAccountName.Enabled = Not blnRegisterSelected
            cmdDeleteAccount.Enabled = Not blnRegisterSelected
            cmdRegen.Enabled = Not blnRegisterSelected
            cmdShowRegister.Enabled = blnRegisterSelected
            cmdDeleteRegister.Enabled = blnRegisterSelected
            cmdEditGenerators.Enabled = blnRegisterSelected
            cmdNewRegister.Enabled = Not blnRegisterSelected
            cmdRegProperties.Enabled = blnRegisterSelected

            Exit Sub
        Catch ex As Exception
            gTopException(ex)
        End Try
    End Sub

    Private Sub lstRegisters_DoubleClick(ByVal eventSender As System.Object, ByVal eventArgs As System.EventArgs) Handles lstRegisters.DoubleClick
        cmdShowRegister_Click(cmdShowRegister, New System.EventArgs())
    End Sub

    Private Sub cmdEditGenerators_Click(sender As Object, e As EventArgs) Handles cmdEditGenerators.Click
        With maudtElement(lstRegisters.SelectedIndex)

            Using frm As New FileListEditorForm
                frm.ShowDialogForPath("Transaction Generators", gstrGeneratorPath(.objAccount, .objReg), _
                    "gen", New TrxGenFilePersister())
            End Using
        End With
    End Sub
End Class