Option Strict On
Option Explicit On

Public Class ReplicaTrx
    Inherits BaseTrx

    Private mstrCatKey As String
    Private mstrPONumber As String
    Private mstrInvoiceNum As String

    Public Sub New(ByVal objReg_ As Register)
        MyBase.New(objReg_)
    End Sub

    Public Overrides ReadOnly Property strCategory As String
        Get
            Return mobjReg.objAccount.objCompany.Categories.strTranslateKey(mstrCatKey)
        End Get
    End Property

    Public Overrides ReadOnly Property strPONumber As String
        Get
            Return mstrPONumber
        End Get
    End Property

    Public Overrides ReadOnly Property strInvoiceNum As String
        Get
            Return mstrInvoiceNum
        End Get
    End Property

    Public Sub NewStartReplica(ByVal blnWillAddToRegister As Boolean, ByVal datDate_ As Date, ByVal strDescription_ As String,
                              ByVal strCatKey_ As String, ByVal strPONumber_ As String, ByVal strInvoiceNum_ As String,
                               ByVal curAmount_ As Decimal, ByVal blnFake_ As Boolean)

        If blnWillAddToRegister Then
            mobjReg.ClearFirstAffected()
        End If

        mstrNumber = "Repl"
        mdatDate = datDate_
        mstrDescription = strDescription_
        mstrCatKey = strCatKey_
        mstrPONumber = strPONumber_
        mstrInvoiceNum = strInvoiceNum_
        mstrMemo = ""
        mlngStatus = TrxStatus.NonBank
        mblnFake = blnFake_
        mblnAwaitingReview = False
        mblnAutoGenerated = False
        mcurAmount = curAmount_

        RaiseErrorOnBadData("NewStartReplica")

    End Sub

    Public Overrides Sub UnApply()
        'Do nothing for ReplicaTrx
    End Sub

    Public Overrides Sub Apply(ByVal blnLoading As Boolean)
        'Do nothing for ReplicaTrx
    End Sub

    Public Overrides Function objClone(ByVal blnWillAddToRegister As Boolean) As BaseTrx
        Dim objReplicaTrx As ReplicaTrx = New ReplicaTrx(mobjReg)
        objReplicaTrx.NewStartReplica(blnWillAddToRegister, mdatDate, mstrDescription, mstrCatKey, mstrPONumber, mstrInvoiceNum, mcurAmount, mblnFake)
        Return objReplicaTrx
    End Function

    Public Overrides ReadOnly Property intTrxTypeSortKey As Integer
        Get
            Return 1
        End Get
    End Property

    Public Overrides ReadOnly Property strDocNumberSortKey As String
        Get
            Return ""
        End Get
    End Property
End Class
