Option Strict On
Option Explicit On

Public Class TransferTrx
    Inherits Trx

    Public Overrides ReadOnly Property lngType As TrxType
        Get
            Return TrxType.glngTRXTYP_TRANSFER
        End Get
    End Property

    Public Overrides Function objClone(objReg As Register) As Trx
        Dim objXferTrx As TransferTrx = New TransferTrx()
        objXferTrx.NewStartTransfer(objReg, mdatDate, mstrDescription, mstrMemo, mblnFake, mblnAwaitingReview, mblnAutoGenerated, mintRepeatSeq, mstrRepeatKey, mstrTransferKey, mcurTransferAmount)
        Return objXferTrx
    End Function

    Public Overrides Function objGetTrxManager(objReg As Register, lngIndex As Integer) As TrxManager
        Return New TransferTrxManager(objReg, lngIndex, Me)
    End Function

    Public Overrides Sub Validate(objReg As Register, lngIndex As Integer)
        MyBase.Validate(objReg, lngIndex)
        If mstrTransferKey = "" Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx requires transfer key")
        End If
        If mstrTransferKey = objReg.strRegisterKey Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot transfer to same register")
        End If
        If Not mcolSplits Is Nothing Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have split collection")
        End If
        If mstrBudgetKey <> "" Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have budget key")
        End If
        If mcurBudgetLimit <> 0 Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have budget limit")
        End If
        If mcurBudgetApplied <> 0 Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have budget applied")
        End If
        If Not mcolAppliedSplits Is Nothing Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have applied splits collection")
        End If
        If mstrImportKey <> "" Then
            objReg.RaiseValidationError(lngIndex, "Transfer trx cannot have import key")
        End If
    End Sub
End Class
