Option Strict On
Option Explicit On

Public Class TrxGenImportData

    Public IsFake As Boolean
    Public NormalMatchRange As Decimal
    Public IsAwaitingReview As Boolean
    Public IsAutoGenerated As Boolean
    Public RepeatSeq As Short
    Public ImportKey As String
    Public RepeatKey As String
    Public NarrowMethod As ImportMatchNarrowMethod

    Public Sub New()
        IsFake = False
        NormalMatchRange = 0D
        IsAwaitingReview = False
        IsAutoGenerated = False
        RepeatSeq = 0
        ImportKey = ""
        RepeatKey = ""
        NarrowMethod = ImportMatchNarrowMethod.None
    End Sub

    Public Shared Function NewFake(ByVal blnFake_ As Boolean) As TrxGenImportData
        Dim result As TrxGenImportData = New TrxGenImportData()
        result.IsFake = blnFake_
        Return result
    End Function

End Class

'Ways to narrow down BaseTrx search results during import.
Public Enum ImportMatchNarrowMethod
    None = 1
    ClosestDate = 2
    EarliestDate = 3
End Enum

