Option Strict Off
Option Explicit On

Public Class TrxGenImportData

    Public blnFake As Boolean
    Public curNormalMatchRange As Decimal
    Public blnAwaitingReview As Boolean
    Public blnAutoGenerated As Boolean
    Public intRepeatSeq As Short
    Public strImportKey As String
    Public strRepeatKey As String
    Public lngNarrowMethod As ImportMatchNarrowMethod

    Public Sub New()
        blnFake = False
        curNormalMatchRange = 0D
        blnAwaitingReview = False
        blnAutoGenerated = False
        intRepeatSeq = 0
        strImportKey = ""
        strRepeatKey = ""
        lngNarrowMethod = ImportMatchNarrowMethod.None
    End Sub

    Public Shared Function NewFake(ByVal blnFake_ As Boolean) As TrxGenImportData
        Dim result As TrxGenImportData = New TrxGenImportData()
        result.blnFake = blnFake_
        Return result
    End Function

End Class
