Option Strict On
Option Explicit On

Imports System.Security.Cryptography

'Code generated by TamperProofCoder.CodeFactory,
'then converted to VB.NET.
Public Class FinancialReportsLicenseValidator
    Inherits Willowsoft.TamperProofData.Validator

    Protected Overrides Function GetPublicKey() As RSAParameters
        Dim rsap As RSAParameters = New RSAParameters()
        rsap.Exponent = New Byte() {1, 0, 1}
        rsap.Modulus = New Byte() {173, 106, 175, 128, 38, 214, 27, 6, 34, 179, 56, 2, 38, 171, 181, 48,
              242, 231, 20, 146, 29, 105, 73, 85, 15, 235, 192, 155, 232, 138, 23, 60,
              79, 178, 235, 231, 67, 182, 160, 39, 44, 147, 203, 41, 216, 207, 84, 146,
              48, 189, 20, 65, 59, 25, 70, 240, 146, 48, 157, 228, 107, 58, 170, 180,
              144, 171, 179, 160, 238, 102, 2, 111, 65, 80, 184, 75, 243, 45, 227, 194,
              9, 156, 216, 245, 212, 11, 93, 81, 199, 243, 53, 4, 135, 22, 216, 79,
              62, 221, 65, 247, 56, 198, 217, 208, 174, 238, 198, 132, 71, 61, 70, 134,
              93, 42, 164, 118, 71, 82, 50, 114, 118, 216, 89, 212, 45, 176, 47, 113}
        Return rsap
    End Function
End Class
