using System;
using System.Collections.Generic;
using System.Management.Automation;

using Willowsoft.CheckBook.Lib;

namespace Willowsoft.CheckBook.Powershell
{

    [Cmdlet(VerbsData.Update, "CheckbookNormalTrx")]
    public class UpdateNormalTrx : Cmdlet
    {
        [Parameter(Mandatory = true)]
        public BankTrx NormalTrx { get; set; }

        [Parameter]
        public DateTime? Date { get; set; }

        [Parameter]
        public string Number { get; set; }

        [Parameter]
        public string Description { get; set; }

        [Parameter]
        public string Memo { get; set; }

        [Parameter]
        public BaseTrx.TrxStatus? Status { get; set; }

        [Parameter]
        public bool? Fake { get; set; }

        [Parameter]
        public bool? AwaitingReview { get; set; }

        [Parameter]
        public decimal? NormalMatchRange { get; set; }

        [Parameter]
        public string ImportKey { get; set; }

        [Parameter]
        public SplitContent OneSplit { get; set; }

        [Parameter]
        public SplitContent[] Splits { get; set; }

        public UpdateNormalTrx()
        {
        }

        protected override void BeginProcessing()
        {
            if (OneSplit == null && Splits == null)
            {
                List<SplitContent> newSplits = new List<SplitContent>();
                foreach(TrxSplit oldSplit in NormalTrx.Splits)
                {
                    newSplits.Add(new SplitContent
                    {
                        strCatKey = oldSplit.CategoryKey,
                        strPONumber = oldSplit.PONumber,
                        strInvoiceNum = oldSplit.InvoiceNum,
                        datInvoice = oldSplit.InvoiceDate,
                        datDue = oldSplit.DueDate,
                        curAmount = oldSplit.Amount,
                        strBudgetKey = oldSplit.BudgetKey,
                        strMemo = oldSplit.Memo,
                        strTerms = oldSplit.Terms
                    });
                }
                Splits = newSplits.ToArray();
            }
            else if (OneSplit != null && Splits != null)
            {
                ThrowTerminatingError(ErrorUtilities.CreateInvalidOperation("-OneSplit and -Splits may not both be specified", "SplitError"));
            }
            NormalTrxManager mgr = new NormalTrxManager(NormalTrx);
            mgr.Update(delegate (BankTrx objTrx)
            {
                objTrx.UpdateStartNormal(
                    strNumber_: !string.IsNullOrEmpty(Number) ? Number : objTrx.Number,
                    datDate_: Date.HasValue ? Date.Value : objTrx.TrxDate,
                    strDescription_: !string.IsNullOrEmpty(Description) ? Description : objTrx.Description,
                    strMemo_: Memo != null ? Memo : objTrx.Memo,
                    lngStatus_: Status.HasValue ? Status.Value : objTrx.Status,
                    blnFake_: Fake.HasValue ? Fake.Value : objTrx.IsFake,
                    curNormalMatchRange_: NormalMatchRange.HasValue ? NormalMatchRange.Value : objTrx.NormalMatchRange,
                    blnAwaitingReview_: AwaitingReview.HasValue ? AwaitingReview.Value : objTrx.IsAwaitingReview,
                    blnAutoGenerated_: false,
                    intRepeatSeq_: objTrx.RepeatSeq,
                    strImportKey_: !string.IsNullOrEmpty(ImportKey) ? ImportKey : objTrx.ImportKey,
                    strRepeatKey_: objTrx.RepeatKey);
                if (OneSplit != null)
                    OneSplit.AddToNormalTrx(objTrx);
                else
                {
                    foreach (SplitContent split in Splits)
                    {
                        split.AddToNormalTrx(objTrx);
                    }
                }
                objTrx.Register.ValidationError += Register_ValidationError;
                try
                {
                    objTrx.Validate();
                    if (TrxValidationError != null)
                        ThrowTerminatingError(ErrorUtilities.CreateInvalidOperation(TrxValidationError, "InvalidTrx"));
                }
                finally
                {
                    objTrx.Register.ValidationError -= Register_ValidationError;
                }
            }, new LogChange(), "PowershellAddNormalTrx");
        }

        private string TrxValidationError = null;

        private void Register_ValidationError(BaseTrx objTrx, string strMsg)
        {
            TrxValidationError = strMsg;
        }
    }
}
