Option Strict On
Option Explicit On

Public Class FilterGeneratedOnly
    Implements ISearchFilter

    Public Function blnInclude(objTrx As BaseTrx) As Boolean Implements ISearchFilter.blnInclude
        Return objTrx.blnAutoGenerated
    End Function

    Public Overrides Function ToString() As String
        Return "Generated Only"
    End Function
End Class
