Option Strict On
Option Explicit On

Public Class FilterNonGenerated
    Implements ISearchFilter

    Public Function IsIncluded(objTrx As BaseTrx) As Boolean Implements ISearchFilter.IsIncluded
        Return Not objTrx.IsAutoGenerated
    End Function

    Public Overrides Function ToString() As String
        Return "All except Generated"
    End Function
End Class
