Option Strict On
Option Explicit On

Public Class FilterNonGenerated
    Implements ISearchFilter

    Public Function blnInclude(objTrx As Trx) As Boolean Implements ISearchFilter.blnInclude
        Return Not objTrx.blnAutoGenerated
    End Function

    Public Overrides Function ToString() As String
        Return "All except Generated"
    End Function
End Class
