Option Strict Off
Option Explicit On

'This interface is used to generate lists of transactions by following
'some rule known to the object and parameters retrieved from an XML file.

Public Interface ITrxGenerator

    '$Description Read parameters from the XML document describing this instance.
    '$Param objDoc The XML document with parameter information.

    Function strLoad(ByVal domDoc As VB6XmlDocument, ByVal objAccount As Account) As String

    '$Description Description of this generator.

    ReadOnly Property strDescription() As String

    '$Description True iff this object should be used to generate transactions.

    ReadOnly Property blnEnabled() As Boolean

    '$Description The repeat key associated with this generator.

    ReadOnly Property strRepeatKey() As String

    '$Description Return a Collection of TrxToCreate from which to create
    '   Trx to add to a register.
    '$Param datEndDate Create no transaction dated later than this. Other
    '   than this constraint, the date range and dates are controlled by
    '   the generator and not the caller.

    Function colCreateTrx(ByVal objReg As Register, ByVal datRptEndMax As Date) As Collection
End Interface

'Data from which one Split can be created by gstrCreateOneTrx().
Public Structure SplitToCreate
    Dim strMemo As String
    Dim strCategoryKey As String
    Dim strPONumber As String
    Dim strInvoiceNum As String
    Dim datInvoiceDate As Date
    Dim datDueDate As Date
    Dim strTerms As String
    Dim strBudgetKey As String
    Dim curAmount As Decimal
End Structure

'Data from which one Trx can be created by gstrCreateOneTrx().
Public Structure TrxToCreate
    Dim strNumber As String
    Dim datDate As Date
    Dim strDescription As String
    Dim strMemo As String
    Dim lngStatus As Trx.TrxStatus
    Dim lngType As Trx.TrxType
    Dim blnFake As Boolean
    Dim blnAutoGenerated As Boolean
    Dim blnAwaitingReview As Boolean
    Dim curNormalMatchRange As Decimal
    Dim strImportKey As String
    Dim intRepeatSeq As Short
    Dim strRepeatKey As String
    Dim intSplits As Short
    Dim adatSplits() As SplitToCreate
    Dim curAmount As Decimal
    Dim strBudgetKey As String
    Dim datBudgetEnds As Date
    Dim lngBudgetUnit As Trx.RepeatUnit
    Dim intBudgetNumber As Short
    Dim strTransferKey As String
End Structure

'Data from which to generate a sequence of dates.
Public Structure DateSequenceParams
    Dim lngRptUnit As Trx.RepeatUnit
    Dim intRptNumber As Short
    Dim datNominalStartDate As Date
    Dim vntNominalEndDate As Object
End Structure
